name: spark_streaming_etl_template
channels:
  - defaults
dependencies:
  - arrow-cpp=3.0.0
  - blas=1.0
  - boost-cpp=1.73.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.3.1
  - double-conversion=3.1.5
  - gflags=2.2.2
  - glog=0.4.0
  - grpc-cpp=1.26.0
  - icu=58.2
  - idna=2.10
  - intel-openmp=2019.4
  - libboost=1.73.0
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libevent=2.1.8
  - libffi=3.3
  - libiconv=1.16
  - libprotobuf=3.11.2
  - libthrift=0.13.0
  - lz4-c=1.9.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1i
  - orc=1.6.5
  - pandas=1.2.1
  - pip=20.3.3
  - py4j=0.10.9
  - pyarrow=3.0.0
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - pyspark=3.0.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytz=2021.1
  - re2=2020.11.01
  - readline=8.1
  - requests=2.25.1
  - setuptools=52.0.0
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.33.0
  - tk=8.6.10
  - uriparser=0.9.3
  - urllib3=1.26.3
  - utf8proc=2.6.1
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - confluent-kafka==1.6.0
